import React from "react";
const columns = [
    { name: "Nome", uid: "name", sortable: true },
    { name: "Título", uid: "title", sortable: true },
    { name: "Síntese", uid: "summary", sortable: true },
    { name: "Última Atualização", uid: "lastUpdated", sortable: true },
    { name: "Status", uid: "status", sortable: true },
    { name: "Ação", uid: "actions" },
  ];

const columns2 = [
  {name: "Status da Contratação", uid: 'status'},
  {name: "Data", uid: 'date'},
  {name: "Horário", uid: 'hour'},
  {name: "Observação", uid: 'observ'},
];

const phaseOptions = [
  {name: "Compilar dossiê", uid: "compile"},
  {name: "Revisão Técnica do dossiê", uid: "review"},
  {name: "Orçamento", uid: "Budget"},
  {name: "Envio da demanda para o ECPN", uid: "demand"},
  {name: "Diligenciamento do processo de contratação", uid: "diligence"},
  {name: "Assinatura do Contrato", uid: "signature"},
  {name: "Divulgação da contratação", uid: "disclosure"},
];

const typeOptions = [
    {name: "ALSO", uid: "also"},
    {name: "ENPI", uid: "enpi"},
    {name: "SMS", uid: "sms"},
    {name: "GIAD", uid: "giad"},
  ];

const contracts = [
    {
      id: 1,
      name: "ALSO-256432",
      title: "Solicitação de óleos para a maquina X",
      summary: "O setor de operações necessita de óleos para realizar a manutenção da maquina X",
      lastUpdated: "2024-01-30",
      phase: "disclosure",
      type:"also",
      statusColor:'success',
      statusHistory: [
        {key: "1" , status: 'Compilar dossiê', date: '2024-01-30', hour: '15:20', observ: ''},
        {key: "2" , status: 'Revisão Técnica do dossiê', date: '2024-01-30', hour: '15:20', observ: ''},
        {key: "3" , status: 'Orçamento', date: '2024-01-30', hour: '15:20', observ: ''},
        {key: "4" , status: 'Envio da demanda para o ECPN', date: '2024-01-30', hour: '15:20', observ: ''},
        {key: "5" , status: 'Diligenciamento do processo de contratação', date: '2024-01-30', hour: '15:20', observ: ''},
        {key: "6" , status: 'Assinatura do Contrato', date: '2024-01-30', hour: '15:20', observ: ''},
        {key: "7" , status: 'Divulgação da contratação', date: '2024-01-30', hour: '15:20', observ: ''},
      ],

    },
    {
        id: 2,
        name: "ENPI-256432",
        title: "Solicitação de óleos para a maquina X",
        summary: "O setor de operações necessita de óleos para realizar a manutenção da maquina X",
        lastUpdated: "2024-01-30",
        phase: "disclosure",
        type:"enpi",
        statusColor:'success',
        statusHistory: [
          {key: "1" , status: 'Compilar dossiê', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "2" , status: 'Revisão Técnica do dossiê', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "3" , status: 'Orçamento', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "4" , status: 'Envio da demanda para o ECPN', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "5" , status: 'Diligenciamento do processo de contratação', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "6" , status: 'Assinatura do Contrato', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "7" , status: 'Divulgação da contratação', date: '2024-01-30', hour: '15:20', observ: ''},
        ],
      },
      {
        id: 3,
        name: "SMS-256432",
        title: "Solicitação de óleos para a maquina X",
        summary: "O setor de operações necessita de óleos para realizar a manutenção da maquina X",
        lastUpdated: "2024-01-30",
        phase: "disclosure",
        type:"sms",
        statusColor:'success',
        statusHistory: [
          {key: "1" , status: 'Compilar dossiê', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "2" , status: 'Revisão Técnica do dossiê', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "3" , status: 'Orçamento', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "4" , status: 'Envio da demanda para o ECPN', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "5" , status: 'Diligenciamento do processo de contratação', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "6" , status: 'Assinatura do Contrato', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "7" , status: 'Divulgação da contratação', date: '2024-01-30', hour: '15:20', observ: ''},
        ],
      },
      {
        id: 4,
        name: "ALSO-256432",
        title: "Solicitação de óleos para a maquina X",
        summary: "O setor de operações necessita de óleos para realizar a manutenção da maquina X",
        lastUpdated: "2024-01-30",
        phase: "disclosure",
        type:"also",
        statusColor:'success',
        statusHistory: [
          {key: "1" , status: 'Compilar dossiê', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "2" , status: 'Revisão Técnica do dossiê', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "3" , status: 'Orçamento', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "4" , status: 'Envio da demanda para o ECPN', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "5" , status: 'Diligenciamento do processo de contratação', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "6" , status: 'Assinatura do Contrato', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "7" , status: 'Divulgação da contratação', date: '2024-01-30', hour: '15:20', observ: ''},
        ],
      },
      {
        id: 5,
        name: "GIAD-256432",
        title: "Solicitação de óleos para a maquina X",
        summary: "O setor de operações necessita de óleos para realizar a manutenção da maquina X",
        lastUpdated: "2024-01-30",
        phase: "disclosure",
        type:"giad",
        statusColor:'success',
        statusHistory: [
          {key: "1" , status: 'Compilar dossiê', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "2" , status: 'Revisão Técnica do dossiê', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "3" , status: 'Orçamento', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "4" , status: 'Envio da demanda para o ECPN', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "5" , status: 'Diligenciamento do processo de contratação', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "6" , status: 'Assinatura do Contrato', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "7" , status: 'Divulgação da contratação', date: '2024-01-30', hour: '15:20', observ: ''},
        ],
      },
      {
        id: 6,
        name: "ALSO-256432",
        title: "Solicitação de óleos para a maquina X",
        summary: "O setor de operações necessita de óleos para realizar a manutenção da maquina X",
        lastUpdated: "2024-01-30",
        phase: "disclosure",
        type:"also",
        statusColor:'success',
        statusHistory: [
          {key: "1" , status: 'Compilar dossiê', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "2" , status: 'Revisão Técnica do dossiê', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "3" , status: 'Orçamento', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "4" , status: 'Envio da demanda para o ECPN', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "5" , status: 'Diligenciamento do processo de contratação', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "6" , status: 'Assinatura do Contrato', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "7" , status: 'Divulgação da contratação', date: '2024-01-30', hour: '15:20', observ: ''},
        ],
      },
      {
        id: 7,
        name: "ALSO-256432",
        title: "Solicitação de óleos para a maquina X",
        summary: "O setor de operações necessita de óleos para realizar a manutenção da maquina X",
        lastUpdated: "2024-01-30",
        phase: "disclosure",
        type:"also",
        statusColor:'success',
        statusHistory: [
          {key: "1" , status: 'Compilar dossiê', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "2" , status: 'Revisão Técnica do dossiê', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "3" , status: 'Orçamento', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "4" , status: 'Envio da demanda para o ECPN', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "5" , status: 'Diligenciamento do processo de contratação', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "6" , status: 'Assinatura do Contrato', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "7" , status: 'Divulgação da contratação', date: '2024-01-30', hour: '15:20', observ: ''},
        ],
      },
      {
        id: 8,
        name: "ALSO-256432",
        title: "Solicitação de óleos para a maquina X",
        summary: "O setor de operações necessita de óleos para realizar a manutenção da maquina X",
        lastUpdated: "2024-01-30",
        phase: "disclosure",
        type:"also",
        statusColor:'success',
        statusHistory: [
          {key: "1" , status: 'Compilar dossiê', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "2" , status: 'Revisão Técnica do dossiê', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "3" , status: 'Orçamento', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "4" , status: 'Envio da demanda para o ECPN', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "5" , status: 'Diligenciamento do processo de contratação', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "6" , status: 'Assinatura do Contrato', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "7" , status: 'Divulgação da contratação', date: '2024-01-30', hour: '15:20', observ: ''},
        ],
      },
      {
        id: 9,
        name: "ALSO-256432",
        title: "Solicitação de óleos para a maquina X",
        summary: "O setor de operações necessita de óleos para realizar a manutenção da maquina X",
        lastUpdated: "2024-01-30",
        phase: "disclosure",
        type:"also",
        statusColor:'success',
        statusHistory: [
          {key: "1" , status: 'Compilar dossiê', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "2" , status: 'Revisão Técnica do dossiê', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "3" , status: 'Orçamento', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "4" , status: 'Envio da demanda para o ECPN', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "5" , status: 'Diligenciamento do processo de contratação', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "6" , status: 'Assinatura do Contrato', date: '2024-01-30', hour: '15:20', observ: ''},
          {key: "7" , status: 'Divulgação da contratação', date: '2024-01-30', hour: '15:20', observ: ''},
        ],
      },
  ];

export {columns, contracts, phaseOptions, typeOptions, columns2};
